New: Switched to ES6 module syntax and jsx template added (fixes: #12)
cgkineo/adapt-submitAll pull request #15
Opened 2024-03-13 14:12 UTC by zubairslamdien

#12

### New
* Now uses ES6 module syntax
* Updated to use a jsx template

2024-04-29 11:14 UTC, kirsty-hames requested changes
This is working as expected thanks @zubairslamdien. Other than the comments raised there's some trailing spaces that can be trimmed.

2024-04-29 11:14 UTC, kirsty-hames commented on templates/submitAll.jsx
> +    onSubmitAllButtonClicked,
Remove comma

2024-04-29 11:14 UTC, kirsty-hames commented on templates/submitAll.jsx
> +    <div className={"btn__container"}>
Remove the curly braces for single classes:
`<div className="btn__container">`

2024-04-29 11:14 UTC, kirsty-hames commented on js/SubmitAllView.js
> +    this.listenTo(Adapt, {
Indentation needs reducing to just 2 spaces.

2024-05-14 17:29 UTC, oliverfoster commented
Would you mind apply the suggestions please? @zubairslamdien

2024-07-15 11:42 UTC, oliverfoster commented
Ready for review

2024-07-15 14:56 UTC, zubairslamdien commented
Checked out and seems good to me. @oliverfoster

2024-07-15 17:29 UTC, merged